Traceback (most recent call last):
  File "/Users/skojaku-admin/miniforge3/envs/advnetsci/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/skojaku-admin/miniforge3/envs/advnetsci/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/skojaku-admin/miniforge3/envs/advnetsci/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/skojaku-admin/miniforge3/envs/advnetsci/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/skojaku-admin/miniforge3/envs/advnetsci/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/skojaku-admin/miniforge3/envs/advnetsci/lib/python3.11/site-packages/nbclient/client.py", line 650, in async_setup_kernel
    yield
  File "/Users/skojaku-admin/miniforge3/envs/advnetsci/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/skojaku-admin/miniforge3/envs/advnetsci/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/skojaku-admin/miniforge3/envs/advnetsci/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------

def tokenize(sequences, vocab):
    retval = []
    for seq in sequences:
        r = []
        for char in seq:
            r.append(vocab.index(char))
        retval.append(r)
    return torch.tensor(retval)

X = tokenize(['ABCDEFGHIJKLMNOPQRST<U>VWXYZ', 'ABCDEFGHIJKLMNOPQRST<V>WXYZ'], vocab)
print("X:", X)
print("Shape of X:", X.shape)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[3], line 10[0m
[1;32m      7[0m         retval[38;5;241m.[39mappend(r)
[1;32m      8[0m     [38;5;28;01mreturn[39;00m torch[38;5;241m.[39mtensor(retval)
[0;32m---> 10[0m X [38;5;241m=[39m tokenize([[38;5;124m'[39m[38;5;124mABCDEFGHIJKLMNOPQRST<U>VWXYZ[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mABCDEFGHIJKLMNOPQRST<V>WXYZ[39m[38;5;124m'[39m], vocab)
[1;32m     11[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mX:[39m[38;5;124m"[39m, X)
[1;32m     12[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mShape of X:[39m[38;5;124m"[39m, X[38;5;241m.[39mshape)

Cell [0;32mIn[3], line 8[0m, in [0;36mtokenize[0;34m(sequences, vocab)[0m
[1;32m      6[0m         r[38;5;241m.[39mappend(vocab[38;5;241m.[39mindex(char))
[1;32m      7[0m     retval[38;5;241m.[39mappend(r)
[0;32m----> 8[0m [38;5;28;01mreturn[39;00m torch[38;5;241m.[39mtensor(retval)

[0;31mValueError[0m: expected sequence of length 28 at dim 1 (got 27)

